trigger:
- main


pool:
  vmImage: ubuntu-latest


jobs:
  - job: createSp2019SingleFarm
    timeoutInMinutes: 0
    cancelTimeoutInMinutes: 1
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'Assinatura do Visual Studio Enterprise â€“ MPN(bed82fbc-918c-4d3c-915a-a571bec7ee87)'
        subscriptionId: 'bed82fbc-918c-4d3c-915a-a571bec7ee87'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'tjsprg'
        location: 'East US'
        templateLocation: 'URL of the file'
        csmFileLink: 'https://raw.githubusercontent.com/macbgit/sp2019farm_v1/main/azuredeploy.json?token=AVE3YF2DGFGDIZTKPKOZEH3BUZ7ZC'
        csmParametersFileLink: 'https://raw.githubusercontent.com/macbgit/sp2019farm_v1/main/azuredeploy.parameters.json?token=AVE3YF7ZXXMLRTACA6XOWE3BUZ74C'
        deploymentMode: 'Incremental'
